name: Deploy to Bluehost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Bluehost
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.mrmprocom.com
        username: elesh@test.mrmprocom.com
        password: Rr0lj!qPfQfK
        port: 21
        protocol: ftp
        local-dir: dist/
        server-dir: /
